library:
  source-dirs: src
tests:
  advent-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
copyright: 2019 Ryan Pilgrim
maintainer: ryan.z.pilgrim@gmail.com
dependencies:
- split
- containers
- unordered-containers
- hashable
- extra
- array
- text
- megaparsec
- base >= 4.7 && < 5
name: advent
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Ryan Pilgrim
github: r-zip/advent
license: BSD3
executables:
  advent-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
description: Please see the README on GitHub at <https://github.com/r-zip/advent#readme>
